production:
  stack: cedar
  app: rubyberlin-672
  config: &default
    BUNDLE_WITHOUT: "development:test"

staging:
  stack: cedar
  app: rubyberlin-staging-563
  config: &default
    BUNDLE_WITHOUT: "development:test"
